[functions.search-company-users]
verify_jwt = true

[functions.public-submit-request]
  verify_jwt = true

[functions.approval-callback]
verify_jwt = false

[functions.notify-requester-assignment]
verify_jwt = false

[functions.public-request-access]
verify_jwt = false

[functions.public-update-request]
verify_jwt = false

[functions.public-approval-access]
verify_jwt = false

[functions.public-approval-action]
verify_jwt = false

[functions.public-assignment-access]
verify_jwt = false

[functions.send-ot-approval-digests]
verify_jwt = false
