type RequestType = 'outside_company' | 'overtime';

type Employee = { employeeId?: string; employeeName?: string; workDescription?: string; workStart?: string; workEnd?: string; totalWeeklyHours?: number; transportRequired?: boolean; busStop?: string };
type RequestData = { requestNo: string; requestType: RequestType; requesterName: string; requesterDepartment?: string; approverName?: string; usingDate: string; startTime: string; endTime: string; pickupLocation: string; destination: string; purpose: string; meetingPoint?: string; withStaff?: boolean; passengers?: string[]; overtimeEmployees?: Employee[] };

const esc = (value: unknown) => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const typeLabel = (type: RequestType) => type === 'overtime' ? 'OVERTIME / HOLIDAY WORK' : 'CAR SERVICE REQUISITION';
const dateLabel = (value: string) => { const match = /^(\d{4})-(\d{2})-(\d{2})/.exec(value || ''); return match ? match[3] + '/' + match[2] + '/' + match[1] : value; };
const timeLabel = (value: string) => String(value ?? '').slice(0, 5);
const row = (label: string, value: unknown) => `<tr><td style="padding:9px 12px;color:#64748b;font-size:13px;width:140px;vertical-align:top;border-bottom:1px solid #e5e7eb">${esc(label)}</td><td style="padding:9px 12px;color:#172033;font-size:14px;font-weight:600;vertical-align:top;border-bottom:1px solid #e5e7eb">${esc(value || '-')}</td></tr>`;
const actionButton = (label: string, url: string, color: string) => `<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin:22px auto 8px"><tr><td bgcolor="${color}" style="border-radius:6px"><a href="${esc(url)}" style="display:inline-block;padding:13px 24px;color:#fff;text-decoration:none;font-size:15px;font-weight:700">${esc(label)}</a></td></tr></table>`;

const details = (data: RequestData) => {
  const common = [row('Request No.', data.requestNo), row('Form', typeLabel(data.requestType)), row('Requester', data.requesterName), row('Department', data.requesterDepartment || '-'), row('Using date', dateLabel(data.usingDate)), row('Time', `${timeLabel(data.startTime)} - ${timeLabel(data.endTime)}`), row('Pickup', data.pickupLocation), row('Destination', data.destination), row('Purpose', data.purpose)].join('');
  const outside = data.requestType === 'outside_company' ? [row('Meeting point', data.meetingPoint === 'loading_area' ? 'Loading Area' : 'Front Area'), row('GA staff', data.withStaff ? 'With staff' : 'Without staff'), row('Passengers', data.passengers?.length ? data.passengers.join(', ') : '-')].join('') : '';
  const employees = data.requestType === 'overtime' && data.overtimeEmployees?.length ? `<div style="margin-top:20px;font-size:15px;font-weight:700">Employee details (${data.overtimeEmployees.length})</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-top:8px;border-collapse:collapse;border:1px solid #dbe3ee"><tr style="background:#eef4fb"><th style="padding:8px;text-align:left;font-size:12px">ID / Employee</th><th style="padding:8px;text-align:left;font-size:12px">Work / Period</th><th style="padding:8px;text-align:left;font-size:12px">Transport</th></tr>${data.overtimeEmployees.map((employee) => `<tr><td style="padding:9px 8px;border-top:1px solid #dbe3ee;font-size:13px;vertical-align:top"><b>${esc(employee.employeeId || '-')}</b><br>${esc(employee.employeeName || '-')}</td><td style="padding:9px 8px;border-top:1px solid #dbe3ee;font-size:13px;vertical-align:top">${esc(employee.workDescription || '-')}<br>${esc(timeLabel(employee.workStart || ''))} - ${esc(timeLabel(employee.workEnd || ''))} - Weekly ${esc(employee.totalWeeklyHours ?? '-')} hrs</td><td style="padding:9px 8px;border-top:1px solid #dbe3ee;font-size:13px;vertical-align:top">${employee.transportRequired ? `Required<br>${esc(employee.busStop || '-')}` : 'Not required'}</td></tr>`).join('')}</table>` : '';
  return `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-top:16px;border-collapse:separate;border-spacing:0;border:1px solid #dbe3ee;border-radius:8px;overflow:hidden">${common}${outside}</table>${employees}`;
};

const layout = (input: { preheader: string; status: string; color: string; title: string; intro: string; content: string; action: string; actionUrl: string; secondaryAction?: string; secondaryUrl?: string; expiresAt: string }) => `<!doctype html><html><body style="margin:0;padding:0;background:#f3f6fa;font-family:Arial,'Segoe UI',sans-serif;color:#172033"><div style="display:none;max-height:0;overflow:hidden;opacity:0">${esc(input.preheader)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f3f6fa;padding:24px 12px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:640px;background:#fff;border:1px solid #dbe3ee;border-radius:10px;overflow:hidden"><tr><td style="background:#173f73;padding:20px 26px;color:#fff"><div style="font-size:20px;font-weight:700">TOKIN Transport</div><div style="font-size:12px;color:#d8e7fb;margin-top:3px">Transportation Request Management</div></td></tr><tr><td style="padding:26px"><span style="display:inline-block;padding:6px 10px;border-radius:999px;background:#eef4fb;color:${input.color};font-size:12px;font-weight:700;text-transform:uppercase">${esc(input.status)}</span><h1 style="font-size:22px;line-height:1.3;margin:14px 0 8px">${esc(input.title)}</h1><p style="font-size:14px;line-height:1.65;margin:0;color:#475569">${esc(input.intro)}</p>${input.content}${actionButton(input.action, input.actionUrl, input.color)}${input.secondaryAction && input.secondaryUrl ? `<div style="text-align:center;margin-top:10px"><a href="${esc(input.secondaryUrl)}" style="color:#1f5fbf;font-size:14px;font-weight:600">${esc(input.secondaryAction)}</a></div>` : ''}<p style="margin:20px 0 0;font-size:11px;line-height:1.55;color:#64748b;word-break:break-all">If the button does not work, copy this address into your browser:<br><a href="${esc(input.actionUrl)}" style="color:#1f5fbf">${esc(input.actionUrl)}</a></p><p style="margin:14px 0 0;padding:10px 12px;background:#fff7ed;border-left:3px solid #f59e0b;font-size:12px;line-height:1.5;color:#9a3412">This secure link expires on ${esc(input.expiresAt)}. Do not forward this email.</p></td></tr><tr><td style="padding:16px 26px;background:#f8fafc;border-top:1px solid #e5e7eb;font-size:11px;color:#64748b">This is an automated message from TOKIN Transport. Please do not reply.</td></tr></table></td></tr></table></body></html>`;

const approvalEmail = (data: RequestData & { approvalUrl: string; expiresAt: string }) => ({ emailSubject: `[Approval required] ${data.requestNo} - ${typeLabel(data.requestType)}`, emailBodyHtml: layout({ preheader: `${data.requestNo} is waiting for your decision.`, status: 'Waiting for approval', color: '#1f5fbf', title: `Please review ${data.requestNo}`, intro: `Dear ${data.approverName || 'Approver'}, review the details and select Approve, Reject, or Request changes.`, content: details(data), action: 'Review and decide', actionUrl: data.approvalUrl, expiresAt: data.expiresAt }) });

const manageEmail = (data: RequestData & { event: string; manageUrl: string; expiresAt: string; comments?: string }) => {
  const changes = data.event === 'request.changes_requested';
  const comments = changes ? `<div style="margin-top:18px;padding:14px 16px;background:#fff7ed;border-left:4px solid #f59e0b"><b style="font-size:12px;color:#9a3412">APPROVER COMMENTS</b><div style="margin-top:5px;font-size:14px;white-space:pre-wrap">${esc(data.comments || 'Please review and update the request.')}</div></div>` : '';
  return { emailSubject: changes ? `[Changes requested] ${data.requestNo}` : `[Request received] ${data.requestNo}`, emailBodyHtml: layout({ preheader: changes ? `${data.requestNo} requires changes.` : `${data.requestNo} was received.`, status: changes ? 'Changes required' : 'Submitted', color: changes ? '#d97706' : '#16794b', title: changes ? `Please update ${data.requestNo}` : 'Your request has been received', intro: changes ? `Dear ${data.requesterName}, the approver requested changes before making a decision.` : `Dear ${data.requesterName}, your request was submitted and is waiting for approval.`, content: `${comments}${details(data)}`, action: changes ? 'Edit and resubmit request' : 'View or manage request', actionUrl: data.manageUrl, expiresAt: data.expiresAt }) };
};

type TransportUnit = { unitId?: string; licensePlate?: string; brand?: string; vehicleType?: string; driverName?: string; driverPhone?: string; employeeIds?: string[] };

const assignmentTransportDetails = (data: RequestData & { vehicle: { licensePlate?: string; brand?: string; model?: string }; driver: { name?: string; phone?: string }; transportUnits?: TransportUnit[]; notes?: string }) => {
  const units = data.transportUnits?.length
    ? data.transportUnits
    : [{ licensePlate: data.vehicle.licensePlate, brand: data.vehicle.brand, vehicleType: data.vehicle.model, driverName: data.driver.name, driverPhone: data.driver.phone }];
  return `<div style="margin-top:20px;font-size:15px;font-weight:700">Vehicles, drivers and passengers (${units.length})</div>${units.map((unit, index) => { const passengers = (unit.employeeIds ?? []).map((employeeId) => data.overtimeEmployees?.find((employee) => employee.employeeId === employeeId)).filter(Boolean) as Employee[]; return `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-top:8px;border:1px solid #cfe3d8;background:#f3fbf6"><tr><td colspan="2" style="padding:9px 12px;background:#e5f5eb;color:#166534;font-size:13px;font-weight:700">Vehicle and driver ${index + 1} ? ${esc(passengers.length)} passengers</td></tr>${row('Vehicle', [unit.licensePlate, unit.brand, unit.vehicleType].filter(Boolean).join(' - '))}${row('Driver', unit.driverName || '-')}${row('Driver phone', unit.driverPhone || '-')}${row('Passengers', passengers.length ? passengers.map((employee) => [employee.employeeName, employee.busStop].filter(Boolean).join(' - ')).join(', ') : '-')}</table>`; }).join('')}${data.notes ? `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-top:8px;border:1px solid #dbe3ee">${row('Admin notes', data.notes)}</table>` : ''}`;
};

const assignmentEmail = (data: RequestData & { vehicle: { licensePlate?: string; brand?: string; model?: string }; driver: { name?: string; phone?: string }; transportUnits?: TransportUnit[]; notes?: string; viewUrl: string; pdfUrl: string; expiresAt: string }) => ({ emailSubject: `[Assignment confirmed] ${data.requestNo} - ${dateLabel(data.usingDate)}`, emailBodyHtml: layout({ preheader: `Vehicle and driver are confirmed for ${data.requestNo}.`, status: 'Assignment confirmed', color: '#16794b', title: 'Transportation is ready', intro: `Dear ${data.requesterName}, the vehicle and driver have been arranged. Check the pickup details before travelling.`, content: `${details(data)}${assignmentTransportDetails(data)}`, action: 'View assignment', actionUrl: data.viewUrl, secondaryAction: 'Download PDF', secondaryUrl: data.pdfUrl, expiresAt: data.expiresAt }) });

export { approvalEmail, assignmentEmail, manageEmail };
