'use client';
import { useState } from 'react';
import { useApp } from './app-provider';
import { Button, Card, Field, Input, Select } from './ui';
import { Driver, Vehicle } from '@/lib/types';
import { AlertTriangle, Plus } from 'lucide-react';
export function Vehicles() {
    const { data, saveVehicle } = useApp(); const [open, setOpen] = useState(false);
    const [form, setForm] = useState({ licensePlate: '', brand: '', model: '', type: 'car', capacity: '4' });
    const save = () => {
        saveVehicle({ id: `v-${Date.now()}`, licensePlate: form.licensePlate, brand: form.brand, model: form.model, type: form.type as Vehicle['type'], capacity: +form.capacity, color: '-', year: new Date().getFullYear(), active: true });
        setOpen(false)
    }; return <Resource title="Vehicle fleet" action={<Button onClick={() => setOpen(!open)}><Plus size={16} />Add vehicle</Button>}>{open && <Card className="mb-4 grid gap-3 p-4 sm:grid-cols-5"><Field label="License plate"><Input value={form.licensePlate} onChange={e => setForm({ ...form, licensePlate: e.target.value })} /></Field><Field label="Brand"><Input value={form.brand} onChange={e => setForm({ ...form, brand: e.target.value })} /></Field><Field label="Model"><Input value={form.model} onChange={e => setForm({ ...form, model: e.target.value })} /></Field><Field label="Type"><Select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option>car</option><option>van</option><option>pickup</option><option>other</option></Select></Field><Field label="Capacity"><Input type="number" value={form.capacity} onChange={e => setForm({ ...form, capacity: e.target.value })} /></Field><Button className="sm:col-span-5" disabled={!form.licensePlate || !form.brand || !form.model} onClick={save}>Save vehicle</Button></Card>}<Table heads={['License plate', 'Vehicle', 'Type', 'Capacity', 'Status']} rows={data.vehicles.map(v => [v.licensePlate, `${v.brand} ${v.model}`, v.type, String(v.capacity), v.active ? 'Active' : 'Inactive'])} /></Resource>
}
export function Drivers() {
    const { data, saveDriver } = useApp(); const [open, setOpen] = useState(false); const [form, setForm] = useState({ employeeId: '', fullName: '', phone: '', licenseNumber: '', licenseExpiry: '' }); const save = () => {
        saveDriver({ id: `d-${Date.now()}`, ...form, active: true }); setOpen(false)
    }; return <Resource title="Driver directory" action={<Button onClick={() => setOpen(!open)}><Plus size={16} />Add driver</Button>}>{open && <Card className="mb-4 grid gap-3 p-4 sm:grid-cols-5">{Object.entries(form).map(([k, v]) => <Field key={k} label={k.replace(/([A-Z])/g, ' $1')}><Input type={k === 'licenseExpiry' ? 'date' : 'text'} value={v} onChange={e => setForm({ ...form, [k]: e.target.value })} /></Field>)}<Button className="sm:col-span-5" disabled={Object.values(form).some(x => !x)} onClick={save}>Save driver</Button></Card>}<div className="grid gap-3 md:grid-cols-2">{data.drivers.map(d => { const soon = (new Date(d.licenseExpiry).getTime() - Date.now()) / 86400000 < 30; return <Card className="p-4" key={d.id}><div className="flex justify-between"><div><p className="font-semibold">{d.fullName}</p><p className="text-sm text-gray-500">{d.employeeId} · {d.phone}</p></div>{soon && <AlertTriangle className="text-amber-600" />}</div><p className="mt-3 text-xs text-gray-500">License {d.licenseNumber} · expires {d.licenseExpiry}</p></Card> })}</div></Resource>
}
function Resource({ title, action, children }: { title: string; action: React.ReactNode; children: React.ReactNode }) { return <><div className="mb-6 flex items-end justify-between"><div><h1 className="text-2xl font-bold">{title}</h1><p className="text-sm text-gray-500">Create and review active operating resources.</p></div>{action}</div>{children}</> }; function Table({ heads, rows }: { heads: string[]; rows: string[][] }) { return <Card className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{heads.map(h => <th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr className="border-t border-line" key={i}>{r.map((v, j) => <td className="px-4 py-3" key={j}>{v}</td>)}</tr>)}</tbody></table></Card> }
