'use client';

import Link from 'next/link';
import { ArrowRight, CalendarCheck, Car, CheckCircle2, Clock3, FilePlus2 } from 'lucide-react';
import { useApp } from '@/components/app-provider';
import { Badge, Card } from '@/components/ui';
import { statusLabel } from '@/lib/business';
export default function Dashboard() {
    const { role, user, data } = useApp();
    const own = data.bookings.filter(b => role === 'requester' ? b.requesterId === user.id : role === 'approver' ? b.department === user.department : role === 'driver' ? b.assignment?.driverId === data.drivers.find(d => d.userId === user.id)?.id : true);
    const pending = own.filter(b => b.status === 'pending_approval').length;
    const active = own.filter(b => ['approved', 'assigned', 'in_progress'].includes(b.status)).length;
    const complete = own.filter(b => b.status === 'completed').length;
    const action = role === 'requester' ? { href: '/bookings/new', label: 'Create request', icon: FilePlus2 } : role === 'approver' ? { href: '/approvals', label: 'Review approvals', icon: CheckCircle2 } : role === 'admin' ? { href: '/admin/bookings', label: 'Manage assignments', icon: Car } : { href: '/driver/trips', label: 'Open my trips', icon: CalendarCheck };
    return <><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase text-brand">{role} workspace</p><h1 className="mt-1 text-2xl font-bold">Welcome, {user.fullName.split(' ')[0]}</h1><p className="mt-1 text-sm text-gray-500">Here is today&apos;s car service activity.</p></div><Link href={action.href} className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-brand px-4 text-sm font-semibold text-white"><action.icon size={18} />{action.label}</Link></div><div className="grid gap-4 sm:grid-cols-3"><Metric label={role === 'approver' ? 'Awaiting your review' : 'Pending approval'} value={pending} icon={<Clock3 />} /><Metric label="Active trips" value={active} icon={<Car />} /><Metric label="Completed" value={complete} icon={<CheckCircle2 />} /></div><div className="mt-6 grid gap-5 lg:grid-cols-[2fr_1fr]"><Card className="p-5"><div className="mb-4 flex justify-between"><h2 className="font-bold">Upcoming activity</h2><Link href={role === 'admin' ? '/admin/bookings' : role === 'driver' ? '/driver/trips' : role === 'approver' ? '/approvals' : '/bookings'} className="flex items-center gap-1 text-sm font-semibold text-brand">View all <ArrowRight size={14} /></Link></div><div className="divide-y divide-line">{own.slice(0, 4).map(b => <Link href={role === 'admin' ? `/admin/bookings/${b.id}` : role === 'approver' ? `/approvals/${b.id}` : role === 'driver' ? `/driver/trips/${b.id}` : `/bookings/${b.id}`} key={b.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-semibold">{b.destination}</p><p className="text-xs text-gray-500">{b.usingDate} · {b.startTime} · {b.bookingNo}</p></div><Badge status={b.status}>{statusLabel(b.status)}</Badge></Link>)}</div></Card><Card className="p-5"><h2 className="font-bold">Fleet snapshot</h2><div className="mt-4 space-y-4"><p className="text-sm"><strong className="text-2xl">{data.vehicles.filter(v => v.active).length}</strong><br /><span className="text-gray-500">active vehicles</span></p><p className="text-sm"><strong className="text-2xl">{data.drivers.filter(d => d.active).length}</strong><br /><span className="text-gray-500">available drivers</span></p></div></Card></div></>
}
function Metric({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <Card className="flex items-center justify-between p-5"><div><p className="text-sm text-gray-500">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></div><div className="grid h-11 w-11 place-items-center rounded-md bg-blue-50 text-brand">{icon}</div></Card> }
